apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proudcity-prod
  namespace: prod
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - secretName: sanrafaelca-tls
    hosts:
    - kube-san-rafael-ca.proudcity.com
    - kube-san-rafael-ca-parks.proudcity.com
  rules:
  - host: kube-san-rafael-ca.proudcity.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: sanrafaelca
          servicePort: 80
  - host: kube-san-rafael-ca-parks.proudcity.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: sanrafaelcaparks
          servicePort: 80
  - host: cityofsanrafael.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: sanrafaelca
          servicePort: 80
  - host: www.cityofsanrafael.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: sanrafaelca
          servicePort: 80
  - host: communityservices.cityofsanrafael.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: sanrafaelcaparks
          servicePort: 80
